t_start_new_story = "Начать новое приключение"
t_go_to_tiger_home = "Пойти в домик Тигра"
t_go_to_hedgehog_home = "Пойти в домик к Ёжику"
t_go_fishing = "Пойти на рыбалку"
t_take_the_rods = "Взять удочки"
t_dig_for_worms = "Копать червей"
t_go_fish_in_pool = "Ловить в луже"
t_go_fish_in_river = "Ловить в речке"
t_go_fish_in_sea = "Ловить в море"

t_go_to_forest = "Пойти в лес"
